---
title: "Random Forest - Detection Frequency"
author: "Leah Lariscy"
output: html_document
---

# Load Packages

```{r}
knitr::opts_chunk$set(message=F)
```

```{r}
library(tidyverse)
library(here)
library(tidymodels)
library(tsibble)
library(ingredients)
library(workboots)
```

# Load Data

```{r}
# n = 6 (original data)
data_n6 <- readRDS(here("data/processed_data/wbe_covid_n6_week.rds")) %>% drop_na()

# n = 5
data_n5 <- readRDS(here("data/processed_data/wbe_covid_n5_week.rds")) %>% drop_na()

# n = 4
data_n4 <- readRDS(here("data/processed_data/wbe_covid_n4_week.rds")) %>% drop_na()

# n = 3
data_n3 <- readRDS(here("data/processed_data/wbe_covid_n3_week.rds")) %>% drop_na()

# n = 2
data_n2 <- readRDS(here("data/processed_data/wbe_covid_n2_week.rds")) %>% drop_na()

# n = 1
data_n1 <- readRDS(here("data/processed_data/wbe_covid_n1_week.rds")) %>% drop_na()
```

# Split data

```{r}
data_n6_train <- data_n6 %>% head(n = 75)
data_n6_test <- data_n6 %>% tail(n = 50)

data_n5_train <- data_n5 %>% head(n = 75)
data_n5_test <- data_n5 %>% tail(n = 50)

data_n4_train <- data_n4 %>% head(n = 75)
data_n4_test <- data_n4 %>% tail(n = 50)

data_n3_train <- data_n3 %>% head(n = 75)
data_n3_test <- data_n3 %>% tail(n = 50)

data_n2_train <- data_n2 %>% head(n = 75)
data_n2_test <- data_n2 %>% tail(n = 50)

data_n1_train <- data_n1 %>% head(n = 75)
data_n1_test <- data_n1 %>% tail(n = 50)
```

# Model prep

## Define model

```{r}
#define linear regression model
lm_model <- linear_reg() %>% 
  set_engine("lm") %>% 
  set_mode("regression") 

#define null model
null_model <- null_model() %>% 
  set_engine("parsnip") %>% 
  set_mode("regression")
```

## Define recipes

```{r}
vl_n6_recipe <- recipe(log10_cases ~ 
              A_N1+A_N2+B_N1+B_N2+C_N1+C_N2+week,
              data = data_n6_train) %>% 
              update_role(week, new_role = "ID") 

vl_n5_recipe <- recipe(log10_cases ~ 
              A_N1+A_N2+B_N1+B_N2+C_N1+C_N2+week,
              data = data_n5_train) %>% 
              update_role(week, new_role = "ID") 

vl_n4_recipe <- recipe(log10_cases ~ 
              A_N1+A_N2+B_N1+B_N2+C_N1+C_N2+week,
              data = data_n4_train) %>% 
              update_role(week, new_role = "ID")

vl_n3_recipe <- recipe(log10_cases ~ 
              A_N1+A_N2+B_N1+B_N2+C_N1+C_N2+week,
              data = data_n3_train) %>% 
              update_role(week, new_role = "ID")

vl_n2_recipe <- recipe(log10_cases ~ 
              A_N1+A_N2+B_N1+B_N2+C_N1+C_N2+week,
              data = data_n2_train) %>% 
              update_role(week, new_role = "ID")

vl_n1_recipe <- recipe(log10_cases ~ 
              A_N1+A_N2+B_N1+B_N2+C_N1+C_N2+week,
              data = data_n1_train) %>% 
              update_role(week, new_role = "ID")
```

## Create workflows

```{r}
#workflow for viral load models (to be tuned)
vl_workflow_n6 <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(vl_n6_recipe)

vl_workflow_n5 <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(vl_n5_recipe)

vl_workflow_n4 <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(vl_n4_recipe)

vl_workflow_n3 <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(vl_n3_recipe)

vl_workflow_n2 <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(vl_n2_recipe)

vl_workflow_n1 <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(vl_n1_recipe)

#workflow for null models
vl_null_workflow_n6 <- workflow() %>% 
  add_model(null_model) %>% 
  add_recipe(vl_n6_recipe)

vl_null_workflow_n1 <- workflow() %>% 
  add_model(null_model) %>% 
  add_recipe(vl_n1_recipe)
```

# Model fitting & CV

## n = 6

```{r}
#fit model to data
set.seed(13)
fit_vl_n6 <- vl_workflow_n6 %>% 
  fit(data = data_n6_train)

#create folds for cross validation
set.seed(13)
folds_vl_n6 <- vfold_cv(data_n6_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
cv_vl_n6 <- fit_resamples(vl_workflow_n6, resamples = folds_vl_n6)

#calculate performance metrics
cv_vl_n6_metrics <- collect_metrics(cv_vl_n6,summarize = F)
vl_n6_metrics_sum <- collect_metrics(cv_vl_n6,summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#check cross validation metrics
vl_n6_metrics_sum
```

### Null model

```{r}
#create folds for cross validation
set.seed(13)
folds_vl_n6_null <- vfold_cv(data_n6_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
cv_vl_n6_null <- fit_resamples(vl_null_workflow_n6, 
                                resamples = folds_vl_n6_null)

#calculate performance metrics
cv_vl_n6_metrics_null <- collect_metrics(cv_vl_n6_null,summarize = F)
vl_n6_metrics_null_sum <- collect_metrics(cv_vl_n6_null,summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#check cross validation metrics
vl_n6_metrics_null_sum
```

## n = 5

```{r}
#fit model to data
set.seed(13)
fit_vl_n5 <- vl_workflow_n5 %>% 
  fit(data = data_n5_train)

#create folds for cross validation
set.seed(13)
folds_vl_n5 <- vfold_cv(data_n5_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
cv_vl_n5 <- fit_resamples(vl_workflow_n5, resamples = folds_vl_n5)

#calculate performance metrics
cv_vl_n5_metrics <- collect_metrics(cv_vl_n5,summarize = F)
vl_n5_metrics_sum <- collect_metrics(cv_vl_n5,summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#check cross validation metrics
vl_n5_metrics_sum
```

## n = 4

```{r}
#fit model to data
set.seed(13)
fit_vl_n4 <- vl_workflow_n4 %>% 
  fit(data = data_n4_train)

#create folds for cross validation
set.seed(13)
folds_vl_n4 <- vfold_cv(data_n4_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
cv_vl_n4 <- fit_resamples(vl_workflow_n4, resamples = folds_vl_n4)

#calculate performance metrics
cv_vl_n4_metrics <- collect_metrics(cv_vl_n4,summarize = F)
vl_n4_metrics_sum <- collect_metrics(cv_vl_n4,summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#check cross validation metrics
vl_n4_metrics_sum
```

## n = 3

```{r}
#fit model to data
set.seed(13)
fit_vl_n3 <- vl_workflow_n3 %>% 
  fit(data = data_n3_train)

#create folds for cross validation
set.seed(13)
folds_vl_n3 <- vfold_cv(data_n3_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
cv_vl_n3 <- fit_resamples(vl_workflow_n3, resamples = folds_vl_n3)

#calculate performance metrics
cv_vl_n3_metrics <- collect_metrics(cv_vl_n3,summarize = F)
vl_n3_metrics_sum <- collect_metrics(cv_vl_n3,summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#check cross validation metrics
vl_n3_metrics_sum
```

## n = 2

```{r}
#fit model to data
set.seed(13)
fit_vl_n2 <- vl_workflow_n2 %>% 
  fit(data = data_n2_train)

#create folds for cross validation
set.seed(13)
folds_vl_n2 <- vfold_cv(data_n2_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
cv_vl_n2 <- fit_resamples(vl_workflow_n2, resamples = folds_vl_n2)

#calculate performance metrics
cv_vl_n2_metrics <- collect_metrics(cv_vl_n2,summarize = F)
vl_n2_metrics_sum <- collect_metrics(cv_vl_n2,summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#check cross validation metrics
vl_n2_metrics_sum
```

## n = 1

```{r}
#fit model to data
set.seed(13)
fit_vl_n1 <- vl_workflow_n1 %>% 
  fit(data = data_n1_train)

#create folds for cross validation
set.seed(13)
folds_vl_n1 <- vfold_cv(data_n1_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
cv_vl_n1 <- fit_resamples(vl_workflow_n1, resamples = folds_vl_n1)

#calculate performance metrics
cv_vl_n1_metrics <- collect_metrics(cv_vl_n1,summarize = F)
vl_n1_metrics_sum <- collect_metrics(cv_vl_n1,summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#check cross validation metrics
vl_n1_metrics_sum
```

### Null model

```{r}
#create folds for cross validation
set.seed(13)
folds_vl_n1_null <- vfold_cv(data_n1_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
cv_vl_n1_null <- fit_resamples(vl_null_workflow_n1, 
                                resamples = folds_vl_n1_null)

#calculate performance metrics
cv_vl_n1_metrics_null <- collect_metrics(cv_vl_n1_null,summarize = F)
vl_n1_metrics_null_sum <- collect_metrics(cv_vl_n1_null,summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#check cross validation metrics
vl_n1_metrics_null_sum
```

## Export results

```{r}
vl_n6_metrics_sum <- vl_n6_metrics_sum %>% mutate(.config="vl_n6",
                                                feature="vl")
vl_n5_metrics_sum <- vl_n5_metrics_sum %>% mutate(.config="vl_n5",
                                                feature="vl")
vl_n4_metrics_sum <- vl_n4_metrics_sum %>% mutate(.config="vl_n4",
                                                feature="vl")
vl_n3_metrics_sum <- vl_n3_metrics_sum %>% mutate(.config="vl_n3",
                                                feature="vl")
vl_n2_metrics_sum <- vl_n2_metrics_sum %>% mutate(.config="vl_n2",
                                                feature="vl")
vl_n1_metrics_sum <- vl_n1_metrics_sum %>% mutate(.config="vl_n1",
                                                feature="vl")

cv_metrics_vl <- rbind(vl_n1_metrics_sum,
                       vl_n2_metrics_sum,
                       vl_n3_metrics_sum,
                       vl_n4_metrics_sum,
                       vl_n5_metrics_sum,
                       vl_n6_metrics_sum)

saveRDS(cv_metrics_vl, 
        here("data/processed_data/linear_reg/cv_metrics_vl.rds"))

#export unsummarized metrics
cv_vl_n6_metrics <- cv_vl_n6_metrics %>% mutate(.config="n6",
                                                feature="vl")
cv_vl_n5_metrics <- cv_vl_n5_metrics %>% mutate(.config="n5",
                                                feature="vl")
cv_vl_n4_metrics <- cv_vl_n4_metrics %>% mutate(.config="n4",
                                                feature="vl")
cv_vl_n3_metrics <- cv_vl_n3_metrics %>% mutate(.config="n3",
                                                feature="vl")
cv_vl_n2_metrics <- cv_vl_n2_metrics %>% mutate(.config="n2",
                                                feature="vl")
cv_vl_n1_metrics <- cv_vl_n1_metrics %>% mutate(.config="n1",
                                                feature="vl")

cv_metrics_vl_raw <- rbind(cv_vl_n6_metrics,
                       cv_vl_n5_metrics,
                       cv_vl_n4_metrics,
                       cv_vl_n3_metrics,
                       cv_vl_n2_metrics,
                       cv_vl_n1_metrics)

saveRDS(cv_metrics_vl_raw, 
        here("data/processed_data/linear_reg/cv_metrics_vl_raw.rds"))
```

# Observed vs predicted

## Training data (2020-2021)

```{r}
# generate predictions from 2000 bootstrap models
set.seed(456)
n6_pred_conf_int_train <- 
  vl_workflow_n6 %>%
  predict_boots(
    n = 2000,
    training_data = data_n6_train,
    new_data = data_n6_train,
    interval = "confidence"
  )

# summarise with a 95% confidence interval
n6_pred_conf_int_train_sum <- n6_pred_conf_int_train %>%
  summarise_predictions()

#select important variables from original data
n6_actual_train <- data_n6_train %>% select(week,log10_cases)

#select important variables from predicted data
n6_pred_train <- n6_pred_conf_int_train_sum %>% select(.pred,.pred_lower,.pred_upper)

#bind original and predicted data and undo log transformation
n6_train_compare <- bind_cols(n6_actual_train, n6_pred_train) %>% 
  mutate(prediction = 10^.pred,
       actual = 10^log10_cases,
       pred_lower = 10^.pred_lower,
       pred_upper = 10^.pred_upper) %>% 
  select(week,actual,prediction,pred_lower,pred_upper)

#calculate R-squared and RMSE
n6_train_rsq <- n6_train_compare %>% 
  rsq(truth = actual, estimate = prediction)

n6_train_rsq

n6_train_rmse <- n6_train_compare %>% 
  rmse(truth = actual,estimate = prediction)

n6_train_rmse

#visualize timeseries of actual vs predicted data
n6_train_compare %>% 
  ggplot(aes(x=week)) +
  geom_line(aes(y=prediction), color = "blue") +
  geom_point(aes(y=prediction), color = "blue") +
  geom_ribbon(aes(ymin=pred_lower, ymax=pred_upper), fill = "blue", alpha = 0.3) +
  geom_line(aes(y=actual), color = "red") +
  geom_point(aes(y=actual), color = "red") +
  ggthemes::theme_clean()

#export files for use in comparison script
saveRDS(n6_train_compare,here(
  "data/processed_data/linear_reg/vl_n6_train_predictions.rds"))

saveRDS(n6_train_rsq,here(
  "data/processed_data/linear_reg/vl_n6_train_rsq.rds"))

saveRDS(n6_train_rmse,here(
  "data/processed_data/linear_reg/vl_n6_train_rmse.rds"))
```

## Testing data (2022)

```{r}
# generate predictions from 2000 bootstrap models
set.seed(456)
n6_pred_conf_int_test <- 
  vl_workflow_n6 %>%
  predict_boots(
    n = 2000,
    training_data = data_n6_train,
    new_data = data_n6_test,
    interval = "confidence"
  )

# summarise with a 95% confidence interval
n6_pred_conf_int_test_sum <- n6_pred_conf_int_test %>%
  summarise_predictions()

#select important variables from original data
n6_actual_test <- data_n6_test %>% select(week,log10_cases)

#select important variables from predicted data
n6_pred_test <- n6_pred_conf_int_test_sum %>% select(.pred,.pred_lower,.pred_upper)

#bind original and predicted data and undo log transformation
n6_test_compare <- bind_cols(n6_actual_test, n6_pred_test) %>% 
  mutate(prediction = 10^.pred,
       actual = 10^log10_cases,
       pred_lower = 10^.pred_lower,
       pred_upper = 10^.pred_upper) %>% 
  select(week,actual,prediction,pred_lower,pred_upper)

#calculate R-squared and RMSE
n6_test_rsq <- n6_test_compare %>% 
  rsq(truth = actual, estimate = prediction)

n6_test_rsq

n6_test_rmse <- n6_test_compare %>% 
  rmse(truth = actual,estimate = prediction)

n6_test_rmse

#visualize timeseries of actual vs predicted data
n6_test_compare %>% 
  ggplot(aes(x=week)) +
  geom_line(aes(y=prediction), color = "blue") +
  geom_point(aes(y=prediction), color = "blue") +
  geom_ribbon(aes(ymin=pred_lower, ymax=pred_upper), fill = "blue", alpha = 0.3) +
  geom_line(aes(y=actual), color = "red") +
  geom_point(aes(y=actual), color = "red") +
  ggthemes::theme_clean()

#export files for use in comparison script
saveRDS(n6_test_compare,here(
  "data/processed_data/rand_forest/vl_n6_test_predictions.rds"))

saveRDS(n6_test_rsq,here(
  "data/processed_data/rand_forest/vl_n6_test_rsq.rds"))

saveRDS(n6_test_rmse,here(
  "data/processed_data/rand_forest/vl_n6_test_rmse.rds"))
```

## Full timeseries

```{r}
# generate predictions from 2000 bootstrap models
set.seed(456)
n6_pred_conf_int_full <- 
  vl_workflow_n6 %>%
  predict_boots(
    n = 2000,
    training_data = data_n6_train,
    new_data = data_n6,
    interval = "confidence"
  )

# summarise with a 95% confidence interval
n6_pred_conf_int_full_sum <- n6_pred_conf_int_full %>%
  summarise_predictions()

#select important variables from original data
n6_actual_full <- data_n6 %>% select(week,log10_cases)

#select important variables from predicted data
n6_pred_full <- n6_pred_conf_int_full_sum %>% select(.pred,.pred_lower,.pred_upper)

#bind original and predicted data and undo log transformation
n6_full_compare <- bind_cols(n6_actual_full, n6_pred_full) %>% 
  mutate(prediction = 10^.pred,
       actual = 10^log10_cases,
       pred_lower = 10^.pred_lower,
       pred_upper = 10^.pred_upper) %>% 
  select(week,actual,prediction,pred_lower,pred_upper)

n6_full_compare %>% 
  ggplot(aes(x=week)) +
  geom_line(aes(y=prediction), color = "blue") +
  geom_point(aes(y=prediction), color = "blue") +
  geom_ribbon(aes(ymin=pred_lower, ymax=pred_upper), fill = "blue", alpha = 0.3) +
  geom_line(aes(y=actual), color = "red") +
  geom_point(aes(y=actual), color = "red") +
  ggthemes::theme_clean()

#export files for use in comparison script
saveRDS(n6_full_compare,here(
  "data/processed_data/linear_reg/vl_n6_full_predictions.rds"))
```
