---
title: "Linear Regression Comparisons"
author: "Leah Lariscy"
output: html_document
---

# Load packages

```{r}
library(tidyverse)
library(here)
library(RColorBrewer)
library(ggpubr)
library(tsibble)
library(yardstick)
```

# Load data

```{r}
#detection frequency
df_metrics <- readRDS(here("data/processed_data/linear_reg/cv_metrics_df.rds"))

#viral load
vl_metrics <- readRDS(here("data/processed_data/linear_reg/cv_metrics_vl.rds"))

#all predictors
all_metrics <- readRDS(here("data/processed_data/linear_reg/cv_metrics_all.rds"))

#bind dataframes
#undo log10 for RMSE
metrics_compare <- rbind(df_metrics,
                         vl_metrics,
                         all_metrics) %>% 
  mutate(config = paste(feature,n,sep = "_"))

saveRDS(metrics_compare,
        here("data/processed_data/linear_reg/metrics_compare.rds"))

#detection frequency n=3 predictions and rsq/rmse
df_n3_train_predictions <- readRDS(here(
  "data/processed_data/linear_reg/df_n3_train_predictions.rds"))
df_n3_train_rsq <- readRDS(here(
  "data/processed_data/linear_reg/df_n3_train_rsq.rds"))
df_n3_train_rmse <- readRDS(here(
  "data/processed_data/linear_reg/df_n3_train_rmse.rds"))

df_n2_test_predictions <- readRDS(here(
  "data/processed_data/linear_reg/df_n2_test_predictions.rds"))
df_n2_test_rsq <- readRDS(here(
  "data/processed_data/linear_reg/df_n2_test_rsq.rds"))
df_n2_test_rmse <- readRDS(here(
  "data/processed_data/linear_reg/df_n2_test_rmse.rds"))


#all predictors n=6 predictions and rsq/rmse
all_n6_train_predictions <- readRDS(here(
  "data/processed_data/linear_reg/all_n6_train_predictions.rds"))
all_n6_train_rsq <- readRDS(here(
  "data/processed_data/linear_reg/all_n6_train_rsq.rds"))
all_n6_train_rmse <- readRDS(here(
  "data/processed_data/linear_reg/all_n6_train_rmse.rds"))

all_n2_test_predictions <- readRDS(here(
  "data/processed_data/linear_reg/all_n2_test_predictions.rds"))
all_n2_test_rsq <- readRDS(here(
  "data/processed_data/linear_reg/all_n2_test_rsq.rds"))
all_n2_test_rmse <- readRDS(here(
  "data/processed_data/linear_reg/all_n2_test_rmse.rds"))
```

# Calculate RMSE/RSQ on new data

```{r}
#calculate for beginning of 2022 (January - April 2022)

#DF 
start_2022_rsq_df <- df_n2_test_predictions %>% 
  head(17) %>% 
  rsq(truth = actual, estimate = prediction)

start_2022_rsq_df

end_2022_rsq_df <- df_n2_test_predictions %>% 
  tail(33) %>% 
  rsq(truth = actual, estimate = prediction)

end_2022_rsq_df

#ALL
start_2022_rsq_all <- all_n2_test_predictions %>% 
  head(17) %>% 
  rsq(truth = actual, estimate = prediction)

start_2022_rsq_all

end_2022_rsq_all <- all_n2_test_predictions %>% 
  tail(33) %>% 
  rsq(truth = actual, estimate = prediction)

end_2022_rsq_all
```

# Visualize

## Make color palette

```{r}
# Extract the last 6 colors from the "Reds", "Greens", and "Blues" palettes
reds <- brewer.pal(9, "Reds")[4:9]
greens <- brewer.pal(9, "Greens")[4:9]
blues <- brewer.pal(9, "Blues")[4:9]

# Combine the colors into a single list
color_palette <- c(reds, greens, blues)

# Display the colors to confirm their distinctiveness
print(color_palette)

# Ensure the list has exactly 18 colors
color_palette <- color_palette[1:18]

# Make list for naming models in ggplot
labels <- c("All 1","All 2","All 3","All 4","All 5","All 6",
            "DF 1","DF 2","DF 3","DF 4","DF 5","DF 6",
            "VL 1","VL 2","VL 3","VL 4","VL 5","VL 6")
```

## RMSE CV training

```{r}
rmse_compare <- metrics_compare %>% 
  ggplot(aes(config, avg_rmse, color=config)) +
  geom_point(size = 4) +
    geom_errorbar(aes(ymin = lower_rmse,
                ymax = upper_rmse)) +
  ggthemes::theme_clean() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        #axis.ticks.x = element_blank(),
        axis.text.x = element_text(angle = 20),
        axis.title = element_text(size = 12,face = "bold"),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12),
        legend.key.height = unit(0.6, "cm"),
        legend.position = "none") + #no legend after all..
  scale_color_manual(name="Configuration",
                    #labels=labels,
                    values = color_palette) +
  scale_x_discrete(labels=labels) +
  geom_hline(yintercept = 250, alpha = 0) +
  geom_hline(yintercept = 100, alpha = 0) +
    geom_hline(yintercept = 192,
             linetype = "longdash",
             linewidth = .8,
             color = "red") +
  annotate("text", label="Null model average", 
           x=16, y=197, size=4, color = "red")

rmse_compare

ggsave(here("figures/linear_reg/metrics/rmse_compare.png"), width = 9, height = 5)

saveRDS(rmse_compare,
        here("figures/linear_reg/metrics/rmse_compare.rds"))
```

```{r}
rmse <- metrics_compare %>% 
  select(model,feature,n,avg_rmse,se_rmse) %>% 
  arrange(avg_rmse)

rmse

saveRDS(rmse,
        here("data/processed_data/linear_reg/rmse_compare.rds"))
```

## RSQ CV training

```{r}
rsq_compare <- metrics_compare %>% 
  ggplot(aes(config, avg_rsq, color=config)) +
  geom_point(size = 4) +
    geom_errorbar(aes(ymin = lower_rsq,
                ymax = upper_rsq)) +
  ggthemes::theme_clean() +
  theme(axis.title.x = element_blank(),
        #axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 20),
        axis.title = element_text(size = 12,face = "bold"),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12),
        legend.key.height = unit(0.6, "cm"),
        legend.position = "none") + #no legend after all..
  scale_color_manual(name="Configuration",
                    #labels=labels,
                    values = color_palette) +
  xlab("Feature selection configuration") +
  ylab("R-Squared") +
  scale_x_discrete(labels=labels) +
  geom_hline(yintercept = 0.8, alpha = 0) +
  geom_hline(yintercept = 0.11,
             linetype = "longdash",
             linewidth = .8,
             color = "red") +
  annotate("text", label="Null model average", 
           x=16, y=.14, size=4, color = "red")

rsq_compare

ggsave(here("figures/linear_reg/metrics/rsq_compare.png"), width = 9, height = 5)

saveRDS(rsq_compare,
        here("figures/linear_reg/metrics/rsq_compare.rds"))
```

```{r}
rsq <- metrics_compare %>% 
  select(model,feature,n,avg_rsq,se_rsq) %>% 
  arrange(desc(avg_rsq))

rsq

saveRDS(rsq,
        here("data/processed_data/linear_reg/rsq_compare.rds"))
```

## Predictions on new data

### All predictors, n = 2

#### Training data (2020-2021)

```{r}
all_n6_train_rsq_round <- all_n6_train_rsq$.estimate %>% round(digits = 3)

all_n6_train_fig <- all_n6_train_predictions %>% 
  ggplot(aes(x=week)) +
  geom_line(aes(y=prediction), color = "#FB6A4A") +
  geom_point(aes(y=prediction), color = "#FB6A4A", shape = 17) +
  geom_ribbon(aes(ymin=pred_lower, ymax=pred_upper), fill = "#FB6A4A", alpha = 0.3) +
  geom_line(aes(y=actual), color = "#003e99") +
  geom_point(aes(y=actual), color = "#003e99", shape = 16) +
  annotate("text", label=all_n6_train_rsq_round, x=18950, y=3250, size=4) +
  annotate("text", label="Predicted", x=18500, y=3050, color="#FB6A4A", size=4) +
  annotate("text", label="Observed", x=18500, y=3250, color="#003e99", size=4) +
  ylab("Weekly cases per 100,000") +
  #xlab("Week") +
  geom_hline(yintercept = 4000, alpha = 0) +
  ggthemes::theme_clean() +
  theme(axis.title = element_text(face = "bold",size = 12),
        axis.title.x = element_blank()) 

all_n6_train_fig

ggsave(here("figures/linear_reg/time_series/all_n6_train.png"))

saveRDS(all_n6_train_fig,
        here("figures/linear_reg/time_series/all_n6_train.rds"))
```

#### New data (2022)

```{r}
all_n2_test1_rsq_round <- start_2022_rsq_all$.estimate %>% 
  round(digits = 3)
all_n2_test2_rsq_round <- end_2022_rsq_all$.estimate %>% 
  round(digits = 3)

all_n2_test_fig <- all_n2_test_predictions %>% 
  ggplot(aes(x=week)) +
  geom_line(aes(y=prediction), color = "#FB6A4A") +
  geom_point(aes(y=prediction), color = "#FB6A4A", shape = 17) +
  geom_ribbon(aes(ymin=pred_lower, ymax=pred_upper), fill = "#FB6A4A", alpha = 0.3) +
  geom_line(aes(y=actual), color = "#003e99") +
  geom_point(aes(y=actual), color = "#003e99", shape = 16) +
  annotate("text", label=all_n2_test1_rsq_round, x=19095, y=2950, size=4) +
  annotate("text", label=all_n2_test2_rsq_round, x=19330, y=2950, size=4) +
  annotate("text", label="Predicted", x=19045, y=2800, color="#FB6A4A", size=4) +
  annotate("text", label="Observed", x=19045, y=2950, color="#003e99", size=4) +
  ylab("Weekly cases per 100,000") +
  #xlab("Week") +
  geom_vline(xintercept = 19115, linetype = 2) +
  #geom_hline(yintercept = 4000, alpha = 0) +
  ggthemes::theme_clean() +
  theme(axis.title = element_text(face = "bold",size = 12),
        axis.title.x = element_blank()) 

all_n2_test_fig

ggsave(here("figures/linear_reg/time_series/all_n2_test.png"))

saveRDS(all_n2_test_fig,
        here("figures/linear_reg/time_series/all_n2_test.rds"))
```

### Detection frequency, n = 3

#### Training data (2020-2021)

```{r}
df_n3_train_rsq_round <- df_n3_train_rsq$.estimate %>% round(digits = 3)

df_n3_train_fig <- df_n3_train_predictions %>% 
  ggplot(aes(x=week)) +
  geom_line(aes(y=prediction), color = "#FB6A4A") +
  geom_point(aes(y=prediction), color = "#FB6A4A", shape = 17) +
  geom_ribbon(aes(ymin=pred_lower, ymax=pred_upper), fill = "#FB6A4A", alpha = 0.3) +
  geom_line(aes(y=actual), color = "#003e99") +
  geom_point(aes(y=actual), color = "#003e99", shape = 16) +
  annotate("text", label=df_n3_train_rsq_round, x=18950, y=3250, size=4) +
  annotate("text", label="Predicted", x=18500, y=3050, color="#FB6A4A", size=4) +
  annotate("text", label="Observed", x=18500, y=3250, color="#003e99", size=4) +
  #ylab("Weekly reported cases") +
  #xlab("Week") +
  geom_hline(yintercept = 4000, alpha = 0) +
  ggthemes::theme_clean() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank())

df_n3_train_fig

ggsave(here("figures/linear_reg/time_series/df_n3_train.png"))

saveRDS(df_n3_train_fig,
        here("figures/linear_reg/time_series/df_n3_train.rds"))
```

#### New data (2022)

```{r}
df_n2_test1_rsq_round <- start_2022_rsq_df$.estimate %>% 
  round(digits = 3)
df_n2_test2_rsq_round <- end_2022_rsq_df$.estimate %>% 
  round(digits = 3)

df_n2_test_fig <- df_n2_test_predictions %>% 
  ggplot(aes(x=week)) +
  geom_line(aes(y=prediction), color = "#FB6A4A") +
  geom_point(aes(y=prediction), color = "#FB6A4A", shape = 17) +
  geom_ribbon(aes(ymin=pred_lower, ymax=pred_upper), fill = "#FB6A4A", alpha = 0.3) +
  geom_line(aes(y=actual), color = "#003e99") +
  geom_point(aes(y=actual), color = "#003e99", shape = 16) +
  annotate("text", label=df_n2_test1_rsq_round, x=19095, y=2950, size=4) +
  annotate("text", label=df_n2_test2_rsq_round, x=19330, y=2950, size=4) +
  annotate("text", label="Predicted", x=19045, y=2800, color="#FB6A4A", size=4) +
  annotate("text", label="Observed", x=19045, y=2950, color="#003e99", size=4) +
  #ylab("Weekly reported cases") +
  #xlab("Week") +
  geom_vline(xintercept = 19115, linetype = 2) +
  #geom_hline(yintercept = 6800, alpha = 0) +
  ggthemes::theme_clean() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank()) 

df_n2_test_fig

ggsave(here("figures/linear_reg/time_series/df_n2_test.png"))

saveRDS(df_n2_test_fig,
        here("figures/linear_reg/time_series/df_n2_test.rds"))
```
