---
title: "Random Forest - Detection Frequency"
author: "Leah Lariscy"
output: html_document
---

# Load Packages

```{r}
knitr::opts_chunk$set(message=F)
```

```{r}
library(tidyverse)
library(here)
library(tidymodels)
library(ggpubr)
library(tsibble)
library(ingredients)
library(RColorBrewer)
library(purrr)
library(workboots)
```

# Load Data

```{r}
# n = 6 (original data)
data_n6 <- readRDS(here("data/processed_data/wbe_covid_n6_week.rds")) %>% drop_na()

# n = 5
data_n5 <- readRDS(here("data/processed_data/wbe_covid_n5_week.rds")) %>% drop_na()

# n = 4
data_n4 <- readRDS(here("data/processed_data/wbe_covid_n4_week.rds")) %>% drop_na()

# n = 3
data_n3 <- readRDS(here("data/processed_data/wbe_covid_n3_week.rds")) %>% drop_na()

# n = 2
data_n2 <- readRDS(here("data/processed_data/wbe_covid_n2_week.rds")) %>% drop_na()

# n = 1
data_n1 <- readRDS(here("data/processed_data/wbe_covid_n1_week.rds")) %>% drop_na()
```

# Split data

```{r}
data_n6_train <- data_n6 %>% head(n = 75)
data_n6_test <- data_n6 %>% tail(n = 50)

data_n5_train <- data_n5 %>% head(n = 75)
data_n5_test <- data_n5 %>% tail(n = 50)

data_n4_train <- data_n4 %>% head(n = 75)
data_n4_test <- data_n4 %>% tail(n = 50)

data_n3_train <- data_n3 %>% head(n = 75)
data_n3_test <- data_n3 %>% tail(n = 50)

data_n2_train <- data_n2 %>% head(n = 75)
data_n2_test <- data_n2 %>% tail(n = 50)

data_n1_train <- data_n1 %>% head(n = 75)
data_n1_test <- data_n1 %>% tail(n = 50)
```

# Model tuning

## Define model

```{r}
#define model
rf_model <- rand_forest(
  mtry = tune(), 
  trees = 1000, 
  min_n = tune()) %>% 
  set_engine("ranger", importance = "permutation") %>% 
  set_mode("regression") 

#define null model
null_model <- null_model() %>% 
  set_engine("parsnip") %>% 
  set_mode("regression")
```

## Define recipes

```{r}
df_n6_recipe <- recipe(log10_cases ~ 
              A_N1_POS+A_N2_POS+B_N1_POS+B_N2_POS+C_N1_POS+C_N2_POS+week,
              data = data_n6_train) %>% 
              update_role(week, new_role = "ID") 

df_n5_recipe <- recipe(log10_cases ~ 
              A_N1_POS+A_N2_POS+B_N1_POS+B_N2_POS+C_N1_POS+C_N2_POS+week,
              data = data_n5_train) %>% 
              update_role(week, new_role = "ID") 

df_n4_recipe <- recipe(log10_cases ~ 
              A_N1_POS+A_N2_POS+B_N1_POS+B_N2_POS+C_N1_POS+C_N2_POS+week,
              data = data_n4_train) %>% 
              update_role(week, new_role = "ID")

df_n3_recipe <- recipe(log10_cases ~ 
              A_N1_POS+A_N2_POS+B_N1_POS+B_N2_POS+C_N1_POS+C_N2_POS+week,
              data = data_n3_train) %>% 
              update_role(week, new_role = "ID")

df_n2_recipe <- recipe(log10_cases ~ 
              A_N1_POS+A_N2_POS+B_N1_POS+B_N2_POS+C_N1_POS+C_N2_POS+week,
              data = data_n2_train) %>% 
              update_role(week, new_role = "ID")

df_n1_recipe <- recipe(log10_cases ~ 
              A_N1_POS+A_N2_POS+B_N1_POS+B_N2_POS+C_N1_POS+C_N2_POS+week,
              data = data_n1_train) %>% 
              update_role(week, new_role = "ID")
```

## Create workflow

```{r}
#workflow for detection frequency models (to be tuned)
df_workflow_n6 <- workflow() %>% 
  add_model(rf_model) %>% 
  add_recipe(df_n6_recipe)

#workflow for null models
df_null_workflow_n6 <- workflow() %>% 
  add_model(null_model) %>% 
  add_recipe(df_n6_recipe)

df_null_workflow_n1 <- workflow() %>% 
  add_model(null_model) %>% 
  add_recipe(df_n1_recipe)
```

## Set up cross-validation

```{r}
set.seed(13)
folds_n6 <- vfold_cv(data_n6_train)
```

## Define tuning grid

```{r}
doParallel::registerDoParallel()

set.seed(345)
tune_rf_1 <- tune_grid(
  df_workflow_n6,
  resamples = folds_n6,
  grid = 20)
```

```{r}
#check RMSE
tune_rf_1 %>%
  collect_metrics() %>%
  filter(.metric == "rmse") %>%
  select(mean, min_n, mtry) %>%
  pivot_longer(min_n:mtry,
    values_to = "value",
    names_to = "parameter"
  ) %>%
  ggplot(aes(value, mean, color = parameter)) +
  geom_point(show.legend = FALSE) +
  facet_wrap(~parameter, scales = "free_x") +
  labs(x = NULL, y = "RMSE")
```

```{r}
#check RSQ
tune_rf_1 %>%
  collect_metrics() %>%
  filter(.metric == "rsq") %>%
  select(mean, min_n, mtry) %>%
  pivot_longer(min_n:mtry,
    values_to = "value",
    names_to = "parameter"
  ) %>%
  ggplot(aes(value, mean, color = parameter)) +
  geom_point(show.legend = FALSE) +
  facet_wrap(~parameter, scales = "free_x") +
  labs(x = NULL, y = "R-Squared")
```

## Select the best model

```{r}
#select the best model based on RMSE
best_rsq_1 <- tune_rf_1 %>%
  select_best(metric = "rsq")

final_rf_1 <- finalize_model(rf_model, best_rsq_1)

final_rf_1
```

# Model fitting & CV

## Create final workflows

```{r}
df_n6_final_wf <- workflow() %>% 
  add_model(final_rf_1) %>% 
  add_recipe(df_n6_recipe)

df_n5_final_wf <- workflow() %>% 
  add_model(final_rf_1) %>% 
  add_recipe(df_n5_recipe)

df_n4_final_wf <- workflow() %>% 
  add_model(final_rf_1) %>% 
  add_recipe(df_n4_recipe)

df_n3_final_wf <- workflow() %>% 
  add_model(final_rf_1) %>% 
  add_recipe(df_n3_recipe)

df_n2_final_wf <- workflow() %>% 
  add_model(final_rf_1) %>% 
  add_recipe(df_n2_recipe)

df_n1_final_wf <- workflow() %>% 
  add_model(final_rf_1) %>% 
  add_recipe(df_n1_recipe)
```

## n = 6

```{r}
#fit model to data
set.seed(13)
fit_df_n6 <- df_n6_final_wf %>% 
  fit(data_n6_train)

saveRDS(fit_df_n6, 
        here("data/processed_data/rand_forest/DF_n6_fit_train.rds"))

#create folds for cross validation
set.seed(13)
folds_df_n6 <- vfold_cv(data_n6_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
control <- control_resamples(save_pred = T)
cv_df_n6 <- fit_resamples(df_n6_final_wf, 
                          resamples = folds_df_n6,
                          control = control)
  
#calculate performance metrics
cv_df_n6_metrics <- collect_metrics(cv_df_n6, summarize = F)
df_n6_metrics_sum <- collect_metrics(cv_df_n6, summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#quick check of performance
df_n6_metrics_sum
```

```{r}
#collect predictions and visualize

#predicted vs observed
collect_predictions(cv_df_n6) %>% 
  ggplot(aes(log10_cases, .pred)) +
  geom_point() +
  stat_poly_line() +
  stat_poly_eq(use_label("eq"))

ggsave(here("figures/model_eval/pred_v_obs/RF_DF.png"))

#residuals
collect_predictions(cv_df_n6) %>% 
  mutate(residual = .pred-log10_cases) %>% 
  ggplot(aes(log10_cases, residual)) +
  geom_point() +
  stat_poly_line() +
  stat_poly_eq(use_label("eq"))

ggsave(here("figures/model_eval/residuals/RF_DF.png"))
```

### Null model

```{r}
#create folds for cross validation
set.seed(13)
folds_df_n6_null <- vfold_cv(data_n6_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
cv_df_n6_null <- fit_resamples(df_null_workflow_n6, 
                                resamples = folds_df_n6_null)
cv_df_n6_metrics_null <- collect_metrics(cv_df_n6_null ,summarize = F)
df_n6_metrics_null_sum <- collect_metrics(cv_df_n6_null ,summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#check cross validation metrics
df_n6_metrics_null_sum
```

## n = 5

```{r}
#fit model to data
set.seed(13)
fit_df_n5 <- df_n5_final_wf %>% 
  fit(data = data_n5_train)

#create folds for cross validation
set.seed(13)
folds_df_n5 <- vfold_cv(data_n5_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
cv_df_n5 <- fit_resamples(df_n5_final_wf, 
                          resamples = folds_df_n5)

cv_df_n5_metrics <- collect_metrics(cv_df_n5,summarize = F)
df_n5_metrics_sum <- collect_metrics(cv_df_n5,summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#check cross validation metrics
df_n5_metrics_sum 
```

## n = 4

```{r}
#fit model to data
set.seed(13)
fit_df_n4 <- df_n4_final_wf %>% 
  fit(data = data_n4_train)

#create folds for cross validation
set.seed(13)
folds_df_n4 <- vfold_cv(data_n4_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
cv_df_n4 <- fit_resamples(df_n4_final_wf, 
                          resamples = folds_df_n4)

cv_df_n4_metrics <- collect_metrics(cv_df_n4,summarize = F)
df_n4_metrics_sum <- collect_metrics(cv_df_n4,summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#check cross validation metrics
df_n4_metrics_sum 
```

## n = 3

```{r}
#fit model to data
set.seed(13)
fit_df_n3 <- df_n3_final_wf %>% 
  fit(data = data_n3_train)

#create folds for cross validation
set.seed(13)
folds_df_n3 <- vfold_cv(data_n3_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
control <- control_resamples(save_pred = T)
cv_df_n3 <- fit_resamples(df_n3_final_wf, 
                          resamples = folds_df_n3,
                          control = control)

cv_df_n3_metrics <- collect_metrics(cv_df_n3,summarize = F)
df_n3_metrics_sum <- collect_metrics(cv_df_n3,summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#check cross validation metrics
df_n3_metrics_sum 
```

### Predictions

```{r}
#return data to original unit
n3_preds_clean <- collect_predictions(cv_df_n3) %>% 
  mutate(cases_observed = 10^log10_cases,
         cases_predicted = 10^.pred) %>% 
select(row=.row, fold=id2, cases_observed, cases_predicted)
```

```{r}
#collect metrics on cleaned data
n3_rmse <- n3_preds_clean %>% 
  group_by(fold) %>% 
  rmse(truth = cases_observed,
       estimate = cases_predicted) %>% 
  summarize(avg_rmse = mean(.estimate),
            se_rmse = sd(.estimate)/n(),
            lower_rmse = avg_rmse-1.96*se_rmse,
            upper_rmse = avg_rmse+1.96*se_rmse)

n3_rsq <- n3_preds_clean %>% 
  group_by(fold) %>% 
  rsq(truth = cases_observed,
      estimate = cases_predicted) %>% 
  summarize(avg_rsq = mean(.estimate),
            se_rsq = sd(.estimate)/n(),
            lower_rsq = avg_rsq-1.96*se_rsq,
            upper_rsq = avg_rsq+1.96*se_rsq)

n3_metrics_sum <- bind_cols(n3_rmse, n3_rsq) %>% 
  mutate(model = "rf",
         feature = "combined",
         n = 3)

n3_metrics_sum

saveRDS(n3_metrics_sum, here("data/processed_data/model_compare/correct_metrics/RF_DF_n3.rds"))
```

```{r}
#predicted vs observed lm
n3_preds_clean %>% 
  ggplot(aes(cases_observed, cases_predicted)) +
  geom_point() +
  ggpmisc::stat_poly_line() +
  stat_poly_eq(use_label("eq"))

ggsave(here("figures/model_eval/pred_v_obs/RF_DF_n3.png"))

#residuals lm
n3_preds_clean %>% 
  mutate(residual = cases_predicted-cases_observed) %>% 
  ggplot(aes(cases_observed, residual)) +
  geom_point() +
  stat_poly_line() +
  stat_poly_eq(use_label("eq"))

ggsave(here("figures/model_eval/residuals/RF_DF_n3.png"))
```

```{r}
#collect predictions
n3_pred_sum <- n3_preds_clean %>% 
  group_by(row) %>% 
  #summarize data
  summarize(cases_observed = mean(cases_observed),
            avg_pred = mean(cases_predicted),
            se_pred = sd(cases_predicted)/n(),
            pred_lower_ci = avg_pred-1.96*se_pred,
            pred_upper_ci = avg_pred+1.96*se_pred)

#plot summarized data
  n3_pred_fig <- n3_pred_sum %>% ggplot(aes(x=row)) +
  geom_line(aes(y=avg_pred), color = "#FB6A4A") +
  geom_point(aes(y=avg_pred), color = "#FB6A4A") +
  geom_line(aes(y=cases_observed), color = "#003e99") +
  #geom_errorbar(aes(ymin = pred_lower_ci,
                    #ymax = pred_upper_ci)) +
  geom_point(aes(y=cases_observed), color = "#003e99") +
  ggthemes::theme_clean()
  
n3_pred_fig

ggsave(here("figures/timeseries/cross_validation/RF_DF_n3.tiff"))
saveRDS(n3_pred_fig, here("figures/timeseries/cross_validation/RF_DF_n3.rds"))
```

### New data

```{r}
n3_new_preds <- predict(fit_df_n3, data_n3_test) %>% 
  bind_cols(data_n3_test)
```

```{r}
#collect predictions
df_n3_pred_sum_test <- n3_new_preds %>%
  #undo log10 normalization
  mutate(cases_observed = 10^log10_cases,
         cases_predicted = 10^.pred) %>% 
  select(week, cases_observed, cases_predicted)
 

 n3_pred_test_fig <- df_n3_pred_sum_test %>% ggplot(aes(x=week)) +
  geom_line(aes(y=cases_predicted), color = "#FB6A4A") +
  geom_point(aes(y=cases_predicted), color = "#FB6A4A") +
  geom_line(aes(y=cases_observed), color = "#003e99") +
  geom_point(aes(y=cases_observed), color = "#003e99") +
  ggthemes::theme_clean()
 
n3_pred_test_fig

ggsave(here("figures/timeseries/cross_validation/RF_DF_n3_test.tiff"))
saveRDS(n3_pred_test_fig, 
        here("figures/timeseries/cross_validation/RF_DF_n3_test.rds"))
saveRDS(df_n3_pred_sum_test, 
        here("data/processed_data/model_compare/new_data/RF_DF_n3_preds.rds"))
```

## n = 2

```{r}
#fit model to data
set.seed(13)
fit_df_n2 <- df_n2_final_wf %>% 
  fit(data = data_n2_train)

#create folds for cross validation
set.seed(13)
folds_df_n2 <- vfold_cv(data_n2_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
cv_df_n2 <- fit_resamples(df_n2_final_wf, 
                          resamples = folds_df_n2)

cv_df_n2_metrics <- collect_metrics(cv_df_n2,summarize = F)
df_n2_metrics_sum <- collect_metrics(cv_df_n2,summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#check cross validation metrics
df_n2_metrics_sum 
```

## n = 1

```{r}
#fit model to data
set.seed(13)
fit_df_n1 <- df_n1_final_wf %>% 
  fit(data = data_n1_train)

#create folds for cross validation
set.seed(13)
folds_df_n1 <- vfold_cv(data_n1_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
cv_df_n1 <- fit_resamples(df_n1_final_wf, 
                          resamples = folds_df_n1)

cv_df_n1_metrics <- collect_metrics(cv_df_n1,summarize = F)
df_n1_metrics_sum <- collect_metrics(cv_df_n1,summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#check cross validation metrics
df_n1_metrics_sum 
```

### Null model

```{r}
#create folds for cross validation
set.seed(13)
folds_df_n1_null <- vfold_cv(data_n1_train, 
                        v = 10,
                        repeats = 10)

#run cross validation
set.seed(13)
cv_df_n1_null <- fit_resamples(df_null_workflow_n1, 
                                resamples = folds_df_n1_null)
cv_df_n1_metrics_null <- collect_metrics(cv_df_n1_null ,summarize = F)
df_n1_metrics_null_sum <- collect_metrics(cv_df_n1_null ,summarize = T) %>% 
  mutate(lower_ci = mean-1.96*std_err,
         upper_ci = mean+1.96*std_err)

#check cross validation metrics
df_n1_metrics_null_sum
```

## Export results

```{r}
cv_df_n6_metrics <- cv_df_n6_metrics %>% mutate(.config="n6",
                                                feature="df")
cv_df_n5_metrics <- cv_df_n5_metrics %>% mutate(.config="n5",
                                                feature="df")
cv_df_n4_metrics <- cv_df_n4_metrics %>% mutate(.config="n4",
                                                feature="df")
cv_df_n3_metrics <- cv_df_n3_metrics %>% mutate(.config="n3",
                                                feature="df")
cv_df_n2_metrics <- cv_df_n2_metrics %>% mutate(.config="n2",
                                                feature="df")
cv_df_n1_metrics <- cv_df_n1_metrics %>% mutate(.config="n1",
                                                feature="df")

cv_metrics_df <- rbind(cv_df_n1_metrics,
                       cv_df_n2_metrics,
                       cv_df_n3_metrics,
                       cv_df_n4_metrics,
                       cv_df_n5_metrics,
                       cv_df_n6_metrics)

saveRDS(cv_metrics_df, 
        here("data/processed_data/rand_forest/cv_metrics_df.rds"))
```

```{r}
cv_df_n6_metrics_sum <- df_n6_metrics_sum %>% mutate(.config="df_n6",
                                                  feature="df")
cv_df_n5_metrics_sum <- df_n5_metrics_sum %>% mutate(.config="df_n5",
                                                  feature="df")
cv_df_n4_metrics_sum <- df_n4_metrics_sum %>% mutate(.config="df_n4",
                                                  feature="df")
cv_df_n3_metrics_sum <- df_n3_metrics_sum %>% mutate(.config="df_n3",
                                                  feature="df")
cv_df_n2_metrics_sum <- df_n2_metrics_sum %>% mutate(.config="df_n2",
                                                  feature="df")
cv_df_n1_metrics_sum <- df_n1_metrics_sum %>% mutate(.config="df_n1",
                                                  feature="df")

cv_metrics_df_sum <- rbind(cv_df_n1_metrics_sum,
                       cv_df_n2_metrics_sum,
                       cv_df_n3_metrics_sum,
                       cv_df_n4_metrics_sum,
                       cv_df_n5_metrics_sum,
                       cv_df_n6_metrics_sum)

saveRDS(cv_metrics_df_sum, 
        here("data/processed_data/rand_forest/cv_metrics_df_sum.rds"))
```

# Observed vs predicted

## Training data (2020-2021)

```{r}
# generate predictions from 2000 bootstrap models
set.seed(456)
n3_pred_conf_int_train <- 
  df_n3_final_wf %>%
  predict_boots(
    n = 2000,
    training_data = data_n3_train,
    new_data = data_n3_train,
    interval = "confidence"
  )

# summarise with a 95% confidence interval
n3_pred_conf_int_train_sum <- n3_pred_conf_int_train %>%
  summarise_predictions()

#select important variables from original data
n3_actual_train <- data_n3_train %>% select(week,log10_cases)

#select important variables from predicted data
n3_pred_train <- n3_pred_conf_int_train_sum %>% select(.pred,.pred_lower,.pred_upper)

#bind original and predicted data and undo log transformation
n3_train_compare <- bind_cols(n3_actual_train, n3_pred_train) %>% 
  mutate(prediction = 10^.pred,
       actual = 10^log10_cases,
       pred_lower = 10^.pred_lower,
       pred_upper = 10^.pred_upper) %>% 
  select(week,actual,prediction,pred_lower,pred_upper)

#calculate R-squared and RMSE
n3_train_rsq <- n3_train_compare %>% 
  rsq(truth = actual, estimate = prediction)

n3_train_rmse <- n3_train_compare %>% 
  rmse(truth = actual,estimate = prediction)

#visualize timeseries of actual vs predicted data
n3_train_compare %>% 
  ggplot(aes(x=week)) +
  geom_line(aes(y=prediction), color = "blue") +
  geom_point(aes(y=prediction), color = "blue") +
  geom_ribbon(aes(ymin=pred_lower, ymax=pred_upper), fill = "blue", alpha = 0.3) +
  geom_line(aes(y=actual), color = "red") +
  geom_point(aes(y=actual), color = "red") +
  ggthemes::theme_clean()

#export files for use in comparison script
saveRDS(n3_train_compare,here(
  "data/processed_data/rand_forest/df_n3_train_predictions.rds"))

saveRDS(n3_train_rsq,here(
  "data/processed_data/rand_forest/df_n3_train_rsq.rds"))

saveRDS(n3_train_rmse,here(
  "data/processed_data/rand_forest/df_n3_train_rmse.rds"))

ggsave(here("figures/random_forest/time_series/df_n3_train.png"))
```

## Testing data (2022)

```{r}
# generate predictions from 2000 bootstrap models
set.seed(456)
n3_pred_conf_int_test <- 
  df_n3_final_wf %>%
  predict_boots(
    n = 2000,
    training_data = data_n3_train,
    new_data = data_n3_test,
    interval = "confidence"
  )

# summarise with a 95% confidence interval
n3_pred_conf_int_test_sum <- n3_pred_conf_int_test %>%
  summarise_predictions()

#select important variables from original data
n3_actual_test <- data_n3_test %>% select(week,log10_cases)

#select important variables from predicted data
n3_pred_test <- n3_pred_conf_int_test_sum %>% select(.pred,.pred_lower,.pred_upper)

#bind original and predicted data and undo log transformation
n3_test_compare <- bind_cols(n3_actual_test, n3_pred_test) %>% 
  mutate(prediction = 10^.pred,
       actual = 10^log10_cases,
       pred_lower = 10^.pred_lower,
       pred_upper = 10^.pred_upper) %>% 
  select(week,actual,prediction,pred_lower,pred_upper)

#calculate R-squared and RMSE
n3_test_rsq <- n3_test_compare %>% 
  rsq(truth = actual, estimate = prediction)

n3_test_rmse <- n3_test_compare %>% 
  rmse(truth = actual,estimate = prediction)

#visualize timeseries of actual vs predicted data
n3_test_compare %>% 
  ggplot(aes(x=week)) +
  geom_line(aes(y=prediction), color = "blue") +
  geom_point(aes(y=prediction), color = "blue") +
  geom_ribbon(aes(ymin=pred_lower, ymax=pred_upper), fill = "blue", alpha = 0.3) +
  geom_line(aes(y=actual), color = "red") +
  geom_point(aes(y=actual), color = "red") +
  ggthemes::theme_clean()

#export files for use in comparison script
saveRDS(n3_test_compare,here(
  "data/processed_data/rand_forest/df_n3_test_predictions.rds"))

saveRDS(n3_test_rsq,here(
  "data/processed_data/rand_forest/df_n3_test_rsq.rds"))

saveRDS(n3_test_rmse,here(
  "data/processed_data/rand_forest/df_n3_test_rmse.rds"))

ggsave(here("figures/random_forest/time_series/df_n3_test.png"))
```

## Full timeseries

```{r}
# generate predictions from 2000 bootstrap models
set.seed(456)
n3_pred_conf_int_full <- 
  df_n3_final_wf %>%
  predict_boots(
    n = 2000,
    training_data = data_n3_train,
    new_data = data_n3,
    interval = "confidence"
  )

# summarise with a 95% confidence interval
n3_pred_conf_int_full_sum <- n3_pred_conf_int_full %>%
  summarise_predictions()

#select important variables from original data
n3_actual_full <- data_n3 %>% select(week,log10_cases)

#select important variables from predicted data
n3_pred_full <- n3_pred_conf_int_full_sum %>% select(.pred,.pred_lower,.pred_upper)

#bind original and predicted data and undo log transformation
n3_full_compare <- bind_cols(n3_actual_full, n3_pred_full) %>% 
  mutate(prediction = 10^.pred,
       actual = 10^log10_cases,
       pred_lower = 10^.pred_lower,
       pred_upper = 10^.pred_upper) %>% 
  select(week,actual,prediction,pred_lower,pred_upper)

n3_full_compare %>% 
  ggplot(aes(x=week)) +
  geom_line(aes(y=prediction), color = "blue") +
  geom_point(aes(y=prediction), color = "blue") +
  geom_ribbon(aes(ymin=pred_lower, ymax=pred_upper), fill = "blue", alpha = 0.3) +
  geom_line(aes(y=actual), color = "red") +
  geom_point(aes(y=actual), color = "red") +
  ggthemes::theme_clean()

#export files for use in comparison script
saveRDS(n3_full_compare,here(
  "data/processed_data/rand_forest/df_n3_full_predictions.rds"))

ggsave(here("figures/random_forest/time_series/df_n3_full.png"))
```
