---
title: "Random Forest Comparisons"
author: "Leah Lariscy"
output: html_document
---

# Load packages

```{r}
library(tidyverse)
library(here)
library(RColorBrewer)
library(vip)
library(tsibble)
library(ggpubr)
```

# Load data

```{r}
#detection frequency metrics
df_metrics <- readRDS(here("data/processed_data/rand_forest/cv_metrics_df_sum.rds"))

#viral load metrics
vl_metrics <- readRDS(here("data/processed_data/rand_forest/cv_metrics_vl_sum.rds"))

#all predictors metrics
all_metrics <- readRDS(here("data/processed_data/rand_forest/cv_metrics_all_sum.rds"))

#bind metrics dataframes
metrics_compare <- rbind(df_metrics,
                         vl_metrics,
                         all_metrics)

#detection frequency n=3 predictions and rsq/rmse
df_n3_train_predictions <- readRDS(here(
  "data/processed_data/rand_forest/df_n3_train_predictions.rds"))
df_n3_train_rsq <- readRDS(here(
  "data/processed_data/rand_forest/df_n3_train_rsq.rds"))
df_n3_train_rmse <- readRDS(here(
  "data/processed_data/rand_forest/df_n3_train_rmse.rds"))

df_n3_test_predictions <- readRDS(here(
  "data/processed_data/rand_forest/df_n3_test_predictions.rds"))
df_n3_test_rsq <- readRDS(here(
  "data/processed_data/rand_forest/df_n3_test_rsq.rds"))
df_n3_test_rmse <- readRDS(here(
  "data/processed_data/rand_forest/df_n3_test_rmse.rds"))

df_n3_full_predictions <- readRDS(here("data/processed_data/rand_forest/df_n3_full_predictions.rds"))


#all predictors n=6 predictions and rsq/rmse
all_n6_train_predictions <- readRDS(here(
  "data/processed_data/rand_forest/all_n6_train_predictions.rds"))
all_n6_train_rsq <- readRDS(here(
  "data/processed_data/rand_forest/all_n6_train_rsq.rds"))
all_n6_train_rmse <- readRDS(here(
  "data/processed_data/rand_forest/all_n6_train_rmse.rds"))

all_n6_test_predictions <- readRDS(here(
  "data/processed_data/rand_forest/all_n6_test_predictions.rds"))
all_n6_test_rsq <- readRDS(here(
  "data/processed_data/rand_forest/all_n6_test_rsq.rds"))
all_n6_test_rmse <- readRDS(here(
  "data/processed_data/rand_forest/all_n6_test_rmse.rds"))

all_n6_full_predictions <- readRDS(here("data/processed_data/rand_forest/all_n6_full_predictions.rds"))

#all predictors n=6 fit (for variable importance viz)
all_n6_train_fit <- readRDS(
  here("data/processed_data/rand_forest/DF_n6_fit_train.rds"))
```

# Visualize

## Make color palette

```{r}
# Extract the last 6 colors from the "Reds", "Greens", and "Blues" palettes
reds <- brewer.pal(9, "Reds")[4:9]
greens <- brewer.pal(9, "Greens")[4:9]
blues <- brewer.pal(9, "Blues")[4:9]

# Combine the colors into a single list
color_palette <- c(reds, greens, blues)

# Display the colors to confirm their distinctiveness
print(color_palette)

# Ensure the list has exactly 18 colors
color_palette <- color_palette[1:18]

# Make list for naming models in ggplot
labels <- c("All 1","All 2","All 3","All 4","All 5","All 6",
            "DF 1","DF 2","DF 3","DF 4","DF 5","DF 6",
            "VL 1","VL 2","VL 3","VL 4","VL 5","VL 6")
```

## RMSE

```{r}
rmse_compare <- metrics_compare %>% 
  filter(.metric == "rmse") %>% 
  ggplot(aes(.config, mean, color=.config)) +
  geom_point(size = 4) +
    geom_errorbar(aes(ymin = lower_ci,
                ymax = upper_ci)) +
  ggthemes::theme_clean() +
  theme(axis.title.x = element_blank(),
        #axis.ticks.x = element_blank(),
        axis.text.x = element_text(angle = 20),
        axis.title.y = element_text(size = 12,face = "bold"),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12),
        legend.key.height = unit(0.6, "cm"),
        legend.position = "none") + #no legend after all..
  scale_color_manual(name="Configuration",
                    #labels=labels,
                    values = color_palette) +
  xlab("Feature selection configuration") +
  ylab("RMSE") +
  scale_x_discrete(labels=labels) +
  geom_hline(yintercept = 0.425, alpha = 0) +
  geom_hline(yintercept = 0.25, alpha = 0)

rmse_compare

ggsave(here("figures/random_forest/metrics/rmse_compare.png"), width = 9, height = 5)

saveRDS(rmse_compare, 
        here("figures/random_forest/metrics/rmse_compare.rds"))
```

```{r}
rmse <- metrics_compare %>% 
  filter(.metric == "rmse") %>% 
  select(mean,.config,feature) %>% 
  arrange(mean) %>% 
  mutate(model = "rand_forest")

rmse

saveRDS(rmse,
        here("data/processed_data/rand_forest/rmse_compare.rds"))
```

## RSQ

```{r}
rsq_compare <- metrics_compare %>% 
  filter(.metric == "rsq") %>% 
  ggplot(aes(.config, mean, color=.config)) +
  geom_point(size = 4) +
    geom_errorbar(aes(ymin = lower_ci,
                ymax = upper_ci)) +
  ggthemes::theme_clean() +
  theme(axis.title.x = element_blank(),
        #axis.ticks.x = element_blank(),
        axis.text.x = element_text(angle = 20),
        axis.title = element_text(size = 12,face = "bold"),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12),
        legend.key.height = unit(0.6, "cm"),
        legend.position = "none") + #no legend after all..
  scale_color_manual(name="Configuration",
                    #labels=labels,
                    values = color_palette) +
  #xlab("Feature selection configuration") +
  ylab("R-Squared") +
  scale_x_discrete(labels=labels) +
  geom_hline(yintercept = 0.73, alpha = 0) +
  geom_hline(yintercept = 0.28, alpha = 0)

rsq_compare

ggsave(here("figures/random_forest/metrics/rsq_compare.png"), width = 9, height = 5)

saveRDS(rsq_compare,
        here("figures/random_forest/metrics/rsq_compare.rds"))
```

```{r}
rsq <- metrics_compare %>% 
  filter(.metric == "rsq") %>% 
  select(mean,.config,feature) %>% 
  arrange(desc(mean)) %>% 
  mutate(model = "rand_forest")

rsq

saveRDS(rsq,
        here("data/processed_data/rand_forest/rsq_compare.rds"))
```

```{r}
mean_rsq <- metrics_compare %>% 
  filter(.metric == "rsq") %>% 
  select(mean,feature) %>% 
  group_by(feature) %>% 
  summarise(mean_rsq=mean(mean)) %>% 
  arrange(desc(mean_rsq)) %>% 
  mutate(model = "rand_forest")
  
mean_rsq

saveRDS(mean_rsq,
        here("data/processed_data/rand_forest/rsq_mean_compare.rds"))
```

## Predictions

### All predictors, n = 6

#### Training data (2020-2021)

```{r}
all_n6_train_rsq_round <- all_n6_train_rsq$.estimate %>% round(digits = 3)

all_n6_train_fig <- all_n6_train_predictions %>% 
  ggplot(aes(x=week)) +
  geom_line(aes(y=prediction), color = "#FB6A4A") +
  geom_point(aes(y=prediction), color = "#FB6A4A", shape = 17) +
  geom_ribbon(aes(ymin=pred_lower, ymax=pred_upper), fill = "#FB6A4A", alpha = 0.3) +
  geom_line(aes(y=actual), color = "#003e99") +
  geom_point(aes(y=actual), color = "#003e99", shape = 16) +
  annotate("text", label=all_n6_train_rsq_round, x=18950, y=1300, size=4) +
  annotate("text", label="Predicted", x=18500, y=1220, color="#FB6A4A", size=4) +
  annotate("text", label="Observed", x=18500, y=1300, color="#003e99", size=4) +
  ylab("Weekly reported cases") +
  #xlab("Week") +
  ggthemes::theme_clean() +
  theme(axis.title = element_text(face = "bold",size = 12),
        axis.title.x = element_blank()) 

all_n6_train_fig

ggsave(here("figures/random_forest/time_series/all_n6_train.png"))

saveRDS(all_n6_train_fig,
        here("figures/random_forest/time_series/all_n6_train.rds"))
```

#### New data (2022)

```{r}
all_n6_test_rsq_round <- all_n6_test_rsq$.estimate %>% round(digits = 3)

all_n6_test_fig <- all_n6_test_predictions %>% 
  ggplot(aes(x=week)) +
  geom_line(aes(y=prediction), color = "#FB6A4A") +
  geom_point(aes(y=prediction), color = "#FB6A4A", shape = 17) +
  geom_ribbon(aes(ymin=pred_lower, ymax=pred_upper), fill = "#FB6A4A", alpha = 0.3) +
  geom_line(aes(y=actual), color = "#003e99") +
  geom_point(aes(y=actual), color = "#003e99", shape = 16) +
  annotate("text", label=all_n6_test_rsq_round, x=19350, y=1500, size=4) +
  annotate("text", label="Predicted", x=19050, y=1410, color="#FB6A4A", size=4) +
  annotate("text", label="Observed", x=19050, y=1500, color="#003e99", size=4) +
  ylab("Weekly reported cases") +
  #xlab("Week") +
  ggthemes::theme_clean() +
  theme(axis.title = element_text(face = "bold",size = 12),
        axis.title.x = element_blank()) 

all_n6_test_fig

ggsave(here("figures/random_forest/time_series/all_n6_test.png"))

saveRDS(all_n6_test_fig,
        here("figures/random_forest/time_series/all_n6_test.rds"))
```

### Detection frequency, n = 3

#### Training data (2020-2021)

```{r}
df_n3_train_rsq_round <- df_n3_train_rsq$.estimate %>% round(digits = 3)

df_n3_train_fig <- df_n3_train_predictions %>% 
  ggplot(aes(x=week)) +
  geom_line(aes(y=prediction), color = "#FB6A4A") +
  geom_point(aes(y=prediction), color = "#FB6A4A", shape = 17) +
  geom_ribbon(aes(ymin=pred_lower, ymax=pred_upper), fill = "#FB6A4A", alpha = 0.3) +
  geom_line(aes(y=actual), color = "#003e99") +
  geom_point(aes(y=actual), color = "#003e99", shape = 16) +
  annotate("text", label=df_n3_train_rsq_round, x=18950, y=1300, size=4) +
  annotate("text", label="Predicted", x=18500, y=1220, color="#FB6A4A", size=4) +
  annotate("text", label="Observed", x=18500, y=1300, color="#003e99", size=4) +
  #ylab("Weekly reported cases") +
  #xlab("Week") +
  ggthemes::theme_clean() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank()) 

df_n3_train_fig

ggsave(here("figures/random_forest/time_series/df_n3_train.png"))

saveRDS(df_n3_train_fig,
        here("figures/random_forest/time_series/df_n3_train.rds"))
```

#### New data (2022)

```{r}
df_n3_test_rsq_round <- df_n3_test_rsq$.estimate %>% round(digits = 3)

df_n3_test_fig <- df_n3_test_predictions %>% 
  ggplot(aes(x=week)) +
  geom_line(aes(y=prediction), color = "#FB6A4A") +
  geom_point(aes(y=prediction), color = "#FB6A4A", shape = 17) +
  geom_ribbon(aes(ymin=pred_lower, ymax=pred_upper), fill = "#FB6A4A", alpha = 0.3) +
  geom_line(aes(y=actual), color = "#003e99") +
  geom_point(aes(y=actual), color = "#003e99", shape = 16) +
  annotate("text", label=df_n3_test_rsq_round, x=19350, y=1500, size=4) +
  annotate("text", label="Predicted", x=19050, y=1410, color="#FB6A4A", size=4) +
  annotate("text", label="Observed", x=19050, y=1500, color="#003e99", size=4) +
  #ylab("Weekly reported cases") +
  #xlab("Week") +
  ggthemes::theme_clean() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank()) 

df_n3_test_fig

ggsave(here("figures/random_forest/time_series/df_n3_test.png"))

saveRDS(df_n3_test_fig,
        here("figures/random_forest/time_series/df_n3_test.rds"))
```

## Variable importance

```{r}
all_variables <- c("Plant A N1 VL","Plant A N1 DF","Plant A N2 VL",
                  "Plant A N2 DF","Plant B N1 VL","Plant B N1 DF",
                  "Plant B N2 VL","Plant B N2 DF","Plant C N1 VL",
                  "Plant C N1 DF","Plant C N2 VL","Plant C N2 DF")

redon_pal <- c("#5B859EFF", "#1E395FFF", "#75884BFF", "#1E5A46FF", "#DF8D71FF", "#AF4F2FFF", "#D48F90FF", "#732F30FF", "#AB84A5FF", "#59385CFF", "#D8B847FF", "#B38711FF")

vip::vip(all_n6_train_fit, 
         mapping = aes(fill = .data[["Variable"]]),
         num_features = 12) +
  ggthemes::theme_clean() +
  scale_fill_manual(values = redon_pal, labels = all_variables) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        #legend.position = "none",
        axis.title.x = element_text(face = "bold",size = 12)) +
  ggtitle("Combined Model Variable Importance Factors") 

ggsave(here("figures/random_forest/variable_importance/vip_all_predictors.png"),
       width = 6, height = 6.5)
```

```{r}
importance <- vi(all_n6_train_fit) %>% 
  arrange(desc(Importance))

importance
```

```{r}
importance_clean <- importance %>% 
  mutate(plant = str_sub(Variable, 1, 1),
         target = str_sub(Variable, 3, 4),
         data_type = if_else(str_detect(Variable, "POS"), "DF", "VL")) %>% 
  select(!Variable)

importance_clean
```

```{r}
#sum importance by plant
importance_clean %>% 
  group_by(plant) %>% 
  summarise(sum = sum(Importance)) %>% 
  arrange(desc(sum))
```

```{r}
#sum importance by plant and gene
importance_clean %>% 
  group_by(plant,target) %>% 
  summarise(sum = sum(Importance)) %>% 
  arrange(desc(sum))
```

```{r}
#sum by plant and data type
importance_clean %>% 
  group_by(plant,data_type) %>% 
  summarise(sum = sum(Importance)) %>% 
  arrange(desc(sum))
```

```{r}
#sum by target
importance_clean %>% 
  group_by(target) %>% 
  summarise(sum = sum(Importance)) %>% 
  arrange(desc(sum))
```

```{r}
#sum by data type
importance_clean %>% 
  group_by(data_type) %>% 
  summarise(sum = sum(Importance)) %>% 
  arrange(desc(sum))
```
